server:
  port: 8011

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8010/eureka

# Hystrix config
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

spring:
  application:
    name: gateway-service
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: account-service
#          uri: http://localhost:8030
#          predicates:
#            - Path=/accounts/**

# Custom property
api:

  login:
    url:
      path: /user-service/users/login

  h2console:
    url:
      path: /user-service/h2-console/**

  registration:
    url:
      path: /user-service/users

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer

token:
  secret: secret1234